[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "readvars"
dynamic = ["version"]
description = 'Read and process EnergyPlus ESO files'
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE.txt" }
keywords = []
authors = [
  { name = "Jason W. DeGraw", email = "jason.degraw@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.optional-dependencies]
test = [
  "pytest>=7",
  "pytest-cov>=4",
]

[project.urls]
Documentation = "https://github.com/Jason W. DeGraw/readvars#readme"
Issues = "https://github.com/Jason W. DeGraw/readvars/issues"
Source = "https://github.com/Jason W. DeGraw/readvars"

[project.scripts]
readvars = "readvars.cli:readvars"
ReadVarsESO = "readvars.cli:readvars"

[tool.hatch.version]
path = "src/readvars/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/readvars"]

[tool.hatch.envs.test]
dependencies = [
  "pytest>=7",
  "pytest-cov>=4",
]

[tool.hatch.envs.test.scripts]
run = "pytest {args:tests}"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/readvars tests}"

[tool.coverage.run]
source_pkgs = ["readvars", "tests"]
branch = true
parallel = true
omit = [
  "src/readvars/__about__.py",
]

[tool.coverage.paths]
readvars = ["src/readvars", "*/readvars/src/readvars"]
tests = ["tests", "*/readvars/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.pytest.ini_options]
addopts = "--strict-markers --strict-config"
pythonpath = ["src"]
testpaths = ["tests"]
